import type { NextPage } from "next";
import Head from "next/head";
import { useState, DOMAttributes } from "react";
import styles from "../styles/Home.module.css";
import { MessagePortal } from "../components/MessagePortal";
import { ModalBasic } from "../components/ModalBasic";
import { ModalHeadlessui } from "../components/ModalHeadlessui";
import { ModalHeadlessuiPos } from "../components/ModalHeadlessuiPos";

const Home: NextPage = () => {
  const [open1, setOpen1] = useState<boolean>(false);
  const [open2, setOpen2] = useState<boolean>(false);
  const [open3, setOpen3] = useState<boolean>(false);
  const [open4, setOpen4] = useState<boolean>(false);
  const [open5, setOpen5] = useState<boolean>(false);
  const [open6, setOpen6] = useState<boolean>(false);

  const handleModal1Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen1(true);
  };
  const handleModal1Close: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen1(false);
  };
  const handleModal2Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen2(true);
  };
  const handleModal2Close: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen2(false);
  };
  const handleModal3Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen3(true);
  };
  const handleModal3Close = () => {
    setOpen3(false);
  };
  const handleModal4Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen4(true);
  };
  const handleModal4Close = () => {
    setOpen4(false);
  };
  const handleModal5Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen5(true);
  };
  const handleModal5Close = () => {
    setOpen5(false);
  };
  const handleModal6Click: DOMAttributes<HTMLButtonElement>["onClick"] = () => {
    setOpen6(true);
  };
  const handleModal6Close = () => {
    setOpen6(false);
  };
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.modalFrame}>
            <button className={styles.button} onClick={handleModal1Click}>
              モーダル画面(portal)起動
            </button>
            <button className={styles.button} onClick={handleModal2Click}>
              モーダル画面起動
            </button>
            <button className={styles.button} onClick={handleModal3Click}>
              モーダル画面(headless-ui)起動
            </button>
          </div>
          <div className={styles.modalFrame}>
            <button className={styles.button} onClick={handleModal4Click}>
              モーダル画面(headless-ui)上側起動
            </button>
            <button className={styles.button} onClick={handleModal5Click}>
              モーダル画面(headless-ui)下側起動
            </button>
            <button className={styles.button} onClick={handleModal6Click}>
              モーダル画面(headless-ui)右側起動
            </button>
          </div>
        </main>
      </div>
      <MessagePortal open={open1} onClick={handleModal1Close} />
      <ModalBasic open={open2} onClick={handleModal2Close} />
      <ModalHeadlessui
        open={open3}
        onClick={handleModal3Close}
        title="title"
        message="Message headless-ui"
      />
      <ModalHeadlessuiPos
        open={open4}
        onClick={handleModal4Close}
        title="title"
        message="Message headless-ui"
        position="top"
      />
      <ModalHeadlessuiPos
        open={open5}
        onClick={handleModal5Close}
        title="title"
        message="Message headless-ui"
        position="bottom"
      />
      <ModalHeadlessuiPos
        open={open6}
        onClick={handleModal6Close}
        title="title"
        message="Message headless-ui"
        position="right"
      />
    </>
  );
};

export default Home;
